version: '2'
services: 
  bot:
    build: .
    container_name: moex_bot
    environment: 
      CHAT_ID: -1001235428121
      API_KEY: <telegram_api_key>
      FIREFOX_ADDRESS: firefox
      # where to store the images
      IMAGE_TMP_PATH: /tmp/
      # browser render timeout
      BROWSER_TIMEOUT: 20000
      # contacts to show each work day
      # the code of contract is used only as a reference
      # the actual parsed contract will be the last active or if it's 3 days before expiration
      # the second one will be parsed and showed.
      CONTRACTS: BR-4.20,RTS-3.20,SI-3.20
      # wether to send the last found article on startup
      # should be false, so it won't potentially spam with already sent articles on crash
      SEND_LAST: "true"
    depends_on: 
      - firefox
    restart: always
  firefox:
    image: deepsweet/firefox-headless-remote:latest
    shm_size: 2g
    ports:
      - 2828:2828
    restart: always
